### ISSUE TITLE
Is it possible to add subscript and superscript option to fonts and make a better experience for selection?

### ISSUE THREAD

**Issue by naivenaive** [JDMCreator/LaTeXTableEditor#24]
This project is really awesome to make journal tables for publishing. We often use superscripts like 'X square ',  is it possible to add subscript and superscript option to font. Most of the time I can only select one cell a time, and has to use ctrl+ click to select two cells. But it is hard to select from A cell to B cell like Excel which makes it hard to change multiple cells at a time. Is it possible to make a better experience for selection?

**Comment by JDMCreator** [comment]
About superscript and subscript, I'm not quite sure that it is a good idea to support this feature because things like "X square" should be done with mathematical expressions, using the `$` icon. You should write `$x^2$` in the editor instead. This project is a table editor and I want to avoid adding too much non-table related features. However, I might examine the option, because I know that in some languages (e.g. french), superscripts are used (e.g. 1er).

You are absolutely right about the selection experience. The next steps in this project will be to improve the selection experience, to finally fix the issues with pasting values and to improve the Undo Manager. However, those are complex issues. In the meantime, you can use `SHIFT + Click` to select from a cell to another. This has been supported for a while.

**Comment by fdchicom** [comment]
Hello there,

Thanks for the table editor! It is my favourite.

I am not sure if it is only me but when I use the mathematical expression using the mathematical icon as proposed ( $x^2$), it does not appear as superscript but instead, the code generated results in undefined~.

could please you give me a hand with this?

Thanks!

**Comment by JDMCreator** [comment]
@fdchicom The issue you mentionned was fixed in the new release. Thank you for your report.

**Comment by JDMCreator** [comment]
Superscript text will be supported in the next release.
